### ISSUE TITLE
figure out how to extract all the vital articles from a Wikipedia dump

### ISSUE THREAD

**Issue by alexrudnick** [hltdi/guampa#11]
Is the "vital article" concept present in every language's Wikipedia, even?

How can we get a list of them?

**Comment by megasser** [comment]
Actually I didn't know about the concept at all until you mentioned it.

Alex Rudnick wrote:

**Comment by alexrudnick** [comment]
So here's the Vital Articles:
http://en.wikipedia.org/wiki/Wikipedia:Vital_articles

Here's the List of articles every Wikipedia should have:
http://meta.wikimedia.org/wiki/List_of_articles_every_Wikipedia_should_have

... and the version for Spanish:
http://es.wikipedia.org/wiki/Wikipedia:Lista_de_art%C3%ADculos_que_toda_Wikipedia_deber%C3%ADa_tener

The first one for es is Muhammad Ali! He is truly the greatest!

**Comment by megasser** [comment]
Wow. What a strange list of people.

Alex Rudnick wrote:

**Comment by alexrudnick** [comment]
OK, believe we're good to go as of b02eb4fb9aa85bb6b3529e642838a4ff4e0f7d04.
