### ISSUE TITLE
have a way to see the previous translations of a given sentence

### ISSUE THREAD

**Issue by alexrudnick** [hltdi/guampa#15]
Also with comments, once we have comments.

**Comment by taylskid** [comment]
This could be related to #16. The "commit"-style comments could offer an easy overview into the history of a translation. Basically, implementing our own little VCS.

**Comment by alexrudnick** [comment]
We have a toy version of this as of 038c54e842b36c59105f1f2c34b676d3d68adf4d -- next to build it into the main interface (as a modal popup, you were thinking?)

Depends somewhat on #22.

**Comment by alexrudnick** [comment]
I'm pretty OK with the current situation. It's not beautiful, but it works. @SirSkidmore, feel free to open another issue to turn it into a modal, if you're feeling it.
