### ISSUE TITLE
Add comments, so you can explain why you put in a particular translation.

### ISSUE THREAD

**Issue by alexrudnick** [hltdi/guampa#16]
Update the database layout.

Or possibly, a comment is just a field on a Translation.

**Comment by taylskid** [comment]
In summary, there are two options here:
- "commit"-like messages for translations, and
- discussions on a translation itself, similar to an issue thread.

Mike will be consulted and then the comments will be implemented using bootstrap-ui from angular-ui.

**Comment by alexrudnick** [comment]
@megasser @albsama -- thoughts? We started that email thread too, but feel free to comment here for the full github experience :)

**Comment by alexrudnick** [comment]
@SirSkidmore I think this is going to take both of us!

So it looks like we'll have Comment objects that know which sentence they go with (and are stored in the db), and then on the history/comments popup, we'll show the whole history of translations along with all the comments...

Hrm. How to interleave them? Do we need to interleave them? Maybe just show two columns, side by side? Keep time stamps? ...

**Comment by alexrudnick** [comment]
Ohh! Maybe a comment doesn't have to pertain to a _sentence_ -- maybe it's about a _translation_. That would help a lot with figuring out the interface.

Could a comment be about a sentence, too, do we think?

**Comment by megasser** [comment]
But what's a translation? A translation of a document/word/sentence? I
think it's OK for comments to pertain to sentences (or translations of
sentences?).

(Is a sentence something that has realizations in both languages? Or is it
just the source language?)

Alex Rudnick wrote:

**Comment by alexrudnick** [comment]
@megasser Ah, pardon! I should be clear about terms.

I'm using sentence in the sense of the class "Sentence" in the system, which is a single source-language sentence. Then "Translation" objects are single target-language sentences that refer to a single Sentence.

**Comment by megasser** [comment]
Ah, OK (should have looked at the code). Then yeah, it makes sense for a
comment to be about a Translation. I could imagine it being about comparing
two or more Translations for a Sentence, but it could just be assigned to
the most recent of these (which wouldn't necessarily be the most recent
Translation of the Sentence).

Alex Rudnick wrote:

**Comment by alexrudnick** [comment]
Simpler proposal! Have a Comment know about its Sentence, but not be about any particular Translation. Then we just have Comments and Translations have timestamps and show them together!

When you view the discussion/history for a sentence, you see all of the comments and all the translations that have been left for it, sorted by time. This seems less confusing, both for users and us as developers -- we don't have to separate out the two things by column or have a way to say which comments went with which translations.

Imagine, for en->es:

source sentence: my hovercraft is full of eels
history (most recent first):
- user C commented "Great work, everybody!"
- user A edited translation: "Mi aerodeslizador está lleno de anguilas."
- user A commented "Oh, I remember that word. It's masculine, though."
- user B edited translation: "Mi aerodeslizador está llena de anguilas."
- user C commented: "Pretty sure hovercrafto isn't the right word in Spanish."
- user A edited translation: "Mi hovercrafto está lleno de anguilas."

**Comment by megasser** [comment]
Yeah, this sounds right to me.

Alex Rudnick wrote:

> Simpler proposal! Have a Comment know about its Sentence, but not be
> about any particular Translation. Then we just have Comments and
> Translations have timestamps and show them together!
> 
> When you view the discussion/history for a sentence, you see all of the
> comments and all the translations that have been left for it, sorted by
> time. This seems less confusing, both for users and us as developers --
> we don't have to separate out the two things by column or have a way to
> say which comments went with which translations.
> 
> Imagine, for en->es:
> 
> source sentence: my hovercraft is full of eels
> history (most recent first):
> - user C commented "Great work, everybody!"
> - user A edited translation: "Mi aerodeslizador está lleno de anguilas."
> - user A commented "Oh, I remember that word. It's masculine, though."
> - user B edited translation: "Mi aerodeslizador está llena de anguilas."
> - user C commented: "Pretty sure hovercrafto isn't the right word in
>   Spanish."
> - user A edited translation: "Mi hovercrafto está lleno de anguilas."
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/hltdi/guampa/issues/16#issuecomment-26464631.

## 

Michael Gasser
Human Language Technology and the Democratization of Information
Tecnologías del Lenguaje Humano y la Democratización de la Información
የሰው ልጅ ቋንቋ ቴክኖሎጂና መረጃ የማግኘት ሥርዓት
www.cs.indiana.edu/~gasser/Research/hltdi.html
