### ISSUE TITLE
initial cut at the main document translation screen

### ISSUE THREAD

**Issue by alexrudnick** [hltdi/guampa#2]
https://github.com/hltdi/guampa/wiki/DocumentEditingScreen

This can just be a mockup -- we'll figure out how to hook it up to the database next.

**Comment by taylskid** [comment]
Basically what we have left to do is the modal comment screen, which I should hopefully be able to get going before this weekend.

**Comment by taylskid** [comment]
Also, some of the Angular code seems broken, revolving around that editing element we removed from the sentences object stuff. Hopefully I can get the form back to only showing up for double clicks without too much hassle, which I know can be done.

**Comment by alexrudnick** [comment]
Also we need to make the interface send translations back up to the server.
