### ISSUE TITLE
have a good story for how to upload new documents to be translated

### ISSUE THREAD

**Issue by alexrudnick** [hltdi/guampa#42]
We don't want to limit ourselves to translating Wikipedia pages.

This will require being able to get the plain text out of documents formatted in, eg, pdf or docx. (probably use Apache Tika for that)

Should all users be able to upload documents?

**Comment by taylskid** [comment]
See 268cda9dfe for current progress on document uploads.

**Comment by alexrudnick** [comment]
This is actually working pretty well now.
