### ISSUE TITLE
write good, concrete instructions for how to deploy the Guampa software on a Linux server

### ISSUE THREAD

**Issue by alexrudnick** [hltdi/guampa#46]
We have a sketch of these right now: https://github.com/hltdi/guampa/wiki/DeployingWithApache

They could be much more complete.

**Comment by taylskid** [comment]
@alexrudnick once you get all of the instructions written out, I can run through the instructions (I'm relatively inexperienced with Apache) and kind of test where the kinks are. 

Until then, I'm going to unassign myself from this issue and let you take care of it. If we want Nginx instructions, I can do those (I do use Nginx)

**Comment by alexrudnick** [comment]
@SirSkidmore Sounds good! I'll write up some better Apache instructions...

**Comment by alexrudnick** [comment]
Done!
https://github.com/hltdi/guampa/wiki/DeployingWithApache

Could use clarification probably, but this should get people started.
