### ISSUE TITLE
clean up the "login" and "create account" pages and make them look nice

### ISSUE THREAD

**Issue by alexrudnick** [hltdi/guampa#48]
They're intentionally crummy looking right now -- make them look good!
- take out the alerts() and the misspellings, especially!
- oh, and they need localization too.

**Comment by taylskid** [comment]
We also might consider separating the manually-created login accounts from the more typical Persona login to make it less confusing for the end-user.

**Comment by alexrudnick** [comment]
OK, it's not terrible! If @albsama has feedback from users, we can change it later, obvs.
