### ISSUE TITLE
if you save a translation but it's equal to the most recent translation, don't save a new copy

### ISSUE THREAD

**Issue by alexrudnick** [hltdi/guampa#49]
Right now, we'll happily save multiple copies of the most recent translation in the history.

**Comment by Mohammedhussen** [comment]
HI Alex,
Congratulation for your successful work. 

---

On Tue, 1/28/14, Alex Rudnick notifications@github.com wrote:

 Subject: [guampa] if you save a translation but it's equal to the most recent translation, don't save a new copy (#49)
 To: "hltdi/guampa" guampa@noreply.github.com
 Date: Tuesday, January 28, 2014, 12:32 PM

 Right now, we'll happily save multiple
 copies of the most recent translation in the history.

 —
 Reply to this email directly or view it on
 GitHub.

**Comment by alexrudnick** [comment]
At least in the js; maybe on the server too, if you feel like it!

**Comment by taylskid** [comment]
I just added client-side validations for this, but on the back-end, how should we approach it?

Does the server return an error?

**Comment by taylskid** [comment]
Server-side validations finished in f43efafc.
