### ISSUE TITLE
only allow one sentence-editing box open at a time

### ISSUE THREAD

**Issue by alexrudnick** [hltdi/guampa#52]
If you open a second one, make sure to close the previous one!

Also, there should maybe be a "close" button to turn off editing.

The open question here: should it automatically save the contents of the box that you're closing, if you click to open a second one?

@albsama , thoughts?

**Comment by taylskid** [comment]
Did we make a decision in regards to what we want to do here? I'm just going to have it automatically save for the time being. Should be pushed up tonight
