### ISSUE TITLE
write the LREC paper camera-ready

### ISSUE THREAD

**Issue by alexrudnick** [hltdi/guampa#53]
The paper got accepted!

Now we need to write the full paper. It should be between 4 and 8 pages, and use the style sheets here:
http://lrec2014.lrec-conf.org/en/submission/authors-kit/

Needs some pictures of the interface, and the text needs to be expanded out from our initial super short abstract.

**Comment by Mohammedhussen** [comment]
congratulations Alex.

**Comment by alexrudnick** [comment]
Done as of yesterday!
